"""add under_determined_dims and rubric versioning fields

Revision ID: fdfcfe5ac73b
Revises: fc778783b597
Create Date: 2026-06-26 03:54:08.695259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdfcfe5ac73b'
down_revision: Union[str, Sequence[str], None] = 'fc778783b597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavioral_signatures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('signature', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('rubric_version', sa.String(), nullable=True),
    sa.Column('bank_version', sa.String(), nullable=True),
    sa.Column('scorer_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_signatures_student_id'), 'behavioral_signatures', ['student_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('option_id', sa.String(), nullable=False),
    sa.Column('response_text', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'scenario_id', name='uq_response_session_scenario')
    )
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('competence_signature', sa.JSON(), nullable=True),
    sa.Column('work_rhythm_signature', sa.JSON(), nullable=True),
    sa.Column('collaboration_signature', sa.JSON(), nullable=True),
    sa.Column('motivation_layer', sa.JSON(), nullable=True),
    sa.Column('confidence_layer', sa.JSON(), nullable=True),
    sa.Column('under_determined_dims', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_scores',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('team_norms', sa.JSON(), nullable=True),
    sa.Column('formation_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('team_scores')
    op.drop_table('students')
    op.drop_table('responses')
    op.drop_index(op.f('ix_behavioral_signatures_student_id'), table_name='behavioral_signatures')
    op.drop_table('behavioral_signatures')
    op.drop_table('assessments')
    # ### end Alembic commands ###
