"""add research infrastructure tables

Revision ID: fe4544b29b36
Revises: b7957d736061
Create Date: 2026-06-16 15:59:24.801834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4544b29b36'
down_revision: Union[str, Sequence[str], None] = 'b7957d736061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('expertise', sa.String(), nullable=True),
    sa.Column('training_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contribution_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('turn_index', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=True),
    sa.Column('response_at', sa.DateTime(), nullable=True),
    sa.Column('char_count', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimension_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_version_id', sa.String(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_span', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('run_purpose', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_annotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('annotator_id', sa.String(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('evidence_spans_json', sa.JSON(), nullable=True),
    sa.Column('annotated_at', sa.DateTime(), nullable=True),
    sa.Column('is_adjudicated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcome_measures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('participant_id', sa.String(), nullable=True),
    sa.Column('measure_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_attributes',
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('language_background', sa.String(), nullable=True),
    sa.Column('is_native_english', sa.String(), nullable=True),
    sa.Column('demographic_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_table('participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('cohort', sa.String(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('consent_version', sa.String(), nullable=True),
    sa.Column('consent_scope', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peer_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('rater_id', sa.String(), nullable=False),
    sa.Column('ratee_id', sa.String(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('signature_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('target_dimensions', sa.JSON(), nullable=True),
    sa.Column('prompt_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_report_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('self_report_responses')
    op.drop_table('scenarios')
    op.drop_table('profile_versions')
    op.drop_table('peer_evaluations')
    op.drop_table('participants')
    op.drop_table('participant_attributes')
    op.drop_table('outcome_measures')
    op.drop_table('human_annotations')
    op.drop_table('extraction_runs')
    op.drop_table('dimension_scores')
    op.drop_table('conversation_turns')
    op.drop_table('contribution_logs')
    op.drop_table('annotators')
    # ### end Alembic commands ###
